vienna-rb/vienna-rb.github.com

source/_posts/2015-01-14-picks.md
=> Aaron added Jan 14 picks

source/_posts/2015-01-21-picks.md
=> Added aaron 2015/01/21 picks

source/_posts/2015-01-28-picks.md
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
=> Added aaron picks 2015-01-28

source/_posts/2015-04-08-picks.md
You said you want it - you get it.
=> Add a single pick from phillipp

source/_posts/2015-04-08-picks.md
Hello,
If you're interested I added three picks for the Apr/8 edition. Keep it up. Cheers.
=> add gerald's picks for Apr/8

source/_posts/2015-04-15-picks.md
Hello,
you might be interested in three new fresh guest picks. Keep it up. Cheers.
=> add apr/15 picks

source/_posts/2015-05-06-picks.md
Hello,
I'd like to submit this week's guest links (for may/6). Highlights a new book, Linuxwochen, etc.  Hope you like it. Keep it up. Cheers.
=> add gerald's picks for May/6

source/_posts/2015-06-10-picks.md
Cool Searchy stuff with Apache Lucene & JRuby.
=> dch picks for 20150610

source/_posts/2015-06-10-picks.md
I hope it's okay that I used inline markdown links.
=> Markus' picks for 2015-06-10

source/_posts/2015-06-17-picks.md
Hello, some pick recommendations from the last (June) meetup plus summer beach reading recommendation. Enjoy the summer. Cheers.
=> add gerald's picks for Jun/17

source/_posts/2015-07-01-picks.md
I wrote this blog last week, maybe it's worth a pick?
=> Picks by Benjamin 2015-07-01

source/_posts/2015-08-05-picks.md
Hello,
For your consideration. Some (more) great Jekyll (static site) links ;-) Thanks for the Jekyll & friends link (e.g. Vienna.html). Keep it up. Enjoy the summer. Cheers.
=> add gerald's picks for Aug/5

source/_posts/2015-08-12-picks.md
Hello,
for your consideration. some more jekyll goodies (incl. free novella for beach reading). Have a great week. Cheers.
=> add gerald's aug/12 picks - more jekyll goodies; free novella

source/_posts/2015-08-26-picks.md
Hello, For your consideration more jekyll (static site) goodies. Have a great week. Keep it up. Cheers
=> add gerald's picks for Aug/28 (more jekyll goodies ;-)

source/_posts/2015-09-02-picks.md
Hello,
For you consideration new picks for Sept/2. This time some sport.db, football.db goodies and the ruby conference calendar (via $ rubyconf) for Sept'15. Keep it up. Cheers.
=> add gerald's picks for Sept/2

source/_posts/2015-10-07-picks.md
As I mentioned before, feel free to move my picks around, especially those from last week.
=> cypher's picks for 2015-10-07

source/_posts/2015-10-14-picks.md
=> Add cypher's picks for 2015-10-14

source/_posts/2015-10-14-picks.md
It is not in the stars to hold our destiny but in ourselves...
=> Add my picks for 14/10 (hope they're still on time!)

source/_posts/2015-11-03-picks.md
Hello,
For your considerations - some jekyll goodies / links and the 1st Vienna.html meetup (Tue Nov/24). Keep it up. Cheers.
=> Add gerald's picks for Nov/3 - Jekyll 3 Release; 1st Vienna.html meetup

source/_posts/2015-12-23-picks.md
Not very christmas-y, but they'll have to suffice :)
=> Picks for 2015-12-23

source/_posts/2016-01-06-picks.md
=> Markus' Picks for 2016-01-06

source/_posts/2016-01-13-picks.md
Getting started with picks ✌️. First link is rather old but one of the best things I came across in the recent weeks (credits to Basti for finding it).
=> max picks 2016-01-13

source/_posts/2016-01-20-picks.md
hope I did everything right:) 
best lauris
=> lauris picks for 2016-01-20

source/_posts/2016-01-27-picks.md
Podcast actually made me laugh out loud when on the train. Second link might be a bit biased - but I really dig postmodern's ruby stuff... 🐼
=> max picks 2016-01-27

source/_posts/2016-01-26-vienna-rb-29-summary.markdown
=> Add summary of the 29th meetup

source/_posts/2016-02-03-picks.md
@alicetragedy   For you consideration - some Jekyll picks for this week's posting. Try to follow up next week with an Middleman edition ;-)  Keep it up. Cheers.
=> gerald's picks for 2016-02-03 (jekyll edit)

source/_posts/2016-02-10-picks.md
Just two from me this week :disappointed:
=> Add ramon's picks for 2016-02-10

source/_posts/2016-02-26-viennarb-number-30-summary.markdown
Better super late than never :sweat:
=> Add 30th edition summary

source/_posts/2016-04-04-vienna-dot-rb-31st-edition-summary.markdown
Just in time for the next one 😓
=> 31st edition summary

source/_posts/2016-05-11-picks.md
=> Add Ramon's pick for 2016-05-11

source/_posts/2016-06-01-picks.md
=> Add Pilar picks for 2016-06-01

source/_posts/2016-06-08-picks.md
=> Add Ramonh's picks for 2016-06-08

source/_posts/2016-07-13-picks.md
=> Add ramonh's pick for 7/13/16

source/_posts/2016-08-31-picks.md
Finally 3 picks, a first in ages 😅
=> Add Ramon's picks for 31.08.2016

2017-02-22-picks.md
=> Adding a pick 😱
